VPYPE_URLS: dict[str, str] = {
    "vpype": "https://vpype.readthedocs.io/en/latest/index.html",
    "crop_input": "https://vpype.readthedocs.io/en/latest/reference.html#cmdoption-read-c",
    "scale": "https://vpype.readthedocs.io/en/latest/reference.html#scaleto",
    "bbox": "https://vpype.readthedocs.io/en/latest/reference.html#bbox",
    "crop": "https://vpype.readthedocs.io/en/stable/reference.html#crop",
    "rotate": "https://vpype.readthedocs.io/en/latest/reference.html#rotate",
    "linemerge": "https://vpype.readthedocs.io/en/latest/reference.html#linemerge",
    "linesort": "https://vpype.readthedocs.io/en/latest/reference.html#linesort",
    "reloop": "https://vpype.readthedocs.io/en/latest/reference.html#reloop",
    "linesimplify": "https://vpype.readthedocs.io/en/latest/reference.html#linesimplify",
    "squiggles": "https://vpype.readthedocs.io/en/latest/reference.html#squiggles",
    "multipass": "https://vpype.readthedocs.io/en/latest/reference.html#multipass",
    "layout": "https://vpype.readthedocs.io/en/latest/reference.html#layout",
    "lineshuffle": "https://vpype.readthedocs.io/en/latest/reference.html#lineshuffle",
    "translate": "https://vpype.readthedocs.io/en/latest/reference.html#translate",
    "dipping": "https://vpype.readthedocs.io/en/latest/cookbook.html#inserting-regular-dipping-patterns-for-plotting-with-paint",
    "splitall": "https://vpype.readthedocs.io/en/latest/reference.html#splitall",
    "splitdist": "https://vpype.readthedocs.io/en/latest/reference.html#cmd-splitdist",
    "occult": "https://github.com/LoicGoulefert/occult", 
    "attribute_parse": "https://vpype.readthedocs.io/en/latest/reference.html#cmdoption-read-a",
    "ldelete": "https://vpype.readthedocs.io/en/latest/reference.html#ldelete",
    "filter": "https://vpype.readthedocs.io/en/latest/reference.html#filter",
}

PPP_URLS: dict[str, str] = {
    "playlist": "https://www.youtube.com/playlist?list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli",
    "whirlwind tour": "https://www.youtube.com/watch?v=cYf2CHCVrv8&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=1",
    "installation": "https://www.youtube.com/watch?v=9a-bJFNydFQ&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=2",
    "updating": "https://www.youtube.com/watch?v=efySJRbtFKQ&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=3",
    "occult": "https://www.youtube.com/watch?v=FsCB30ovM3M&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=4",
    "decompose": "https://www.youtube.com/watch?v=yKCYRsWuM60&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=5",
    "compose": "https://www.youtube.com/watch?v=vLzsAa7OzjM&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=6",
    "process": "https://www.youtube.com/watch?v=oUNUyBV6oDA&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=7",
    "paint": "https://www.youtube.com/watch?v=PCdTkyd2ADI&list=PL9Kq-2ltl3B4Dl3438KB67FPoJSAxnbli&index=8",
}